name: Check docs

on:
  push:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10
      - name: Test the coverage check
        run: uv run python -m unittest discover -s scripts
      - name: Check documentation coverage
        run: uv run scripts/check-docs.py
